package com.rentpulse.navigation

object Routes {
    const val Welcome = "welcome"
    const val CreateAccount = "create_account"
    const val SignIn = "sign_in"
    const val AccountVerification = "account_verification"
    const val PasswordReset = "password_reset"
    const val TenantProfileCreation ="tenant_profile_creation"
    const val TenantDashboard = "tenant_dashboard"
    const val RolesScreen = "roles"
    const val PasswordResetSuccess = "password_reset_success"
    const val LandlordProfileCreation = "landlord_profile_creation"
    const val LandlordPersonalInfo = "landlord_personal_info"
    const val LandlordPropertyInfo = "landlord_property_info"
    const val LandlordPaymentInfo = "landlord_payment_info"
    const val HelpCenter = "help_center"
    const val TermsOfService = "terms_of_service"
    const val LandlordDashboard = "landlord_dashboard"
    const val AboutRentPulse = "about_rent_pulse"
    const val PrivacyPolicy = "privacy_policy"
    const val LandlordPaymentMethod = "landlord_payment_method"
    const val TenantLeaseDetails = "tenant_lease_details"
    const val TenantLeaseSubmissionReview = "tenant_lease_submission_review"
    const val TenantPaymentDashboard = "tenant_payment_dashboard"
    const val TenantSettings = "tenant_settings"
    const val TenantPaymentHistory = "tenant_payment_history"
    const val TenantLeaseVerification = "tenant_lease_verification"
    const val TenantLeaseVerificationStatus = "tenant_lease_verification_status"
    const val TenantPayment = "tenant_payment"
    const val TenantPaymentReceipt = "tenant_payment_receipt"
    const val LandlordProperties = "landlord_properties"
    const val LandlordAddProperty = "landlord_add_property"
    const val LandlordSettings = "landlord_settings"
    const val LandlordSupport = "landlord_support"
}